services:
  - type: web
    name: digital-divas-captioner
    env: docker
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
    autoDeploy: true